# Generated by Django 3.2.9 on 2021-12-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
