# Generated by Django 3.2.9 on 2021-12-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_card', '0002_auto_20211206_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='stage',
            field=models.CharField(default='剛登入', max_length=50),
        ),
    ]
