# Generated by Django 3.2.9 on 2021-12-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_card', '0003_alter_user_info_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('student_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('student_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Machi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('student_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('student_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user_info',
            name='stage',
            field=models.CharField(default='尚未建立會員', max_length=50),
        ),
    ]
