# Generated by Django 3.2.9 on 2021-12-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_card', '0004_auto_20211206_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='point',
        ),
    ]
