# Generated by Django 3.2.9 on 2021-12-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_card', '0007_auto_20211208_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='student_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='uid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
