# Generated by Django 3.2.9 on 2021-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_card', '0012_auto_20211208_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('getpoint', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hotpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('getpoint', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Machi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('getpoint', models.IntegerField(default=0)),
            ],
        ),
    ]
