# Generated by Django 3.2.9 on 2021-12-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_card', '0013_github_hotpot_machi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jolin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('getpoint', models.IntegerField(default=0)),
                ('flg', models.BooleanField(default=0)),
            ],
        ),
    ]
