# Generated by Django 3.2.9 on 2021-12-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_card', '0015_remove_jolin_flg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jolin',
        ),
    ]
