# Generated by Django 3.2.9 on 2021-12-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_card', '0017_cck'),
    ]

    operations = [
        migrations.AddField(
            model_name='cck',
            name='flg',
            field=models.BooleanField(default=0),
        ),
    ]
