# Generated by Django 3.2.9 on 2021-12-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_card', '0019_remove_cck_flg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='stage',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
